### ISSUE TITLE
abapCi seems to ignore settigs

### ISSUE THREAD

**Issue by gepparta** [andau/abapCI#1]
first of all, a very nice idea.
we need more of this in abap :-)

Issue:
If you switch off abapCi in settings, abapCI seems still to process something.  
At least it keeps appearing in the right corner of IDE every 3 seconds

**Comment by andau** [comment]
Currently (in the last version from 19.03.2018) the plugin is activated if there is the Dashboard view or the Main View opened. To deactivate the plugin you can simply close the two views and restart Eclipse. If somebody opens one of the above mentioned views I assume he or she wants to use at least one function of the plugin :-)  
 
The CI Job is triggered if an activation is performed. The job itself seems to run for approx. 30 seconds. In reality the job runs ones then after 10 seconds again and one final check is done at 30 seconds after the activation. 

This 3-times handling is because the activation is asynchronous and I want to give immediate feedback for a small activation but also catch an activation with a lot of files.

Hopes this helps.

**Comment by TimoJohn** [comment]
Hello Andreas, 
I experience the same issues Alex does, ABAP CI keep checking again and again. 

Secondly, if I run my unittests manual, the results are not used in the ABAPCI Views ( times are not updated )

**Comment by andau** [comment]
Hmm, do you have the latest version 0.2.3 installed. In this version it should run only on activations like described above. 
Also an manual run in the main view changes the date.
