### ISSUE TITLE
Run Unit Tests on save ( Settings )

### ISSUE THREAD

**Issue by TimoJohn** [andau/abapCI#2]
Hello Andreas, 
for my understanding it does not make sense in ABAP to run the unit test after SAVE as it would use the old load of code.  
=> Pls Change to "after Activation"

**Comment by andau** [comment]
I run the unit test after the activation, see the description in issue 1.
Well due to the fact that the activation is asynchronous without feedback to the Eclipse editor it can happen that in rare cases the first run takes some old code. But in nearly all cases the 10 second run should get the activated code and the 30 second run should cover the rest. 
Thats not yet an ideal approach, so ideas welcome.
