### ISSUE TITLE
FeatureRequest - Formatter

### ISSUE THREAD

**Issue by zapik** [andau/abapCI#20]
Hello,

it would be great to have some formatter/beautifier that could enforce custom rules to solve formatting discrepancies in team (like indentation of IF's, method calls etc.) ?
Or are you aware about such tool?

#autoformat is nice, but Pretty Print is unfortunately not so powerful...

Feel free to close this as it not real issue :)

**Comment by flaiker** [comment]
I started implementing this over here: [prettier-printer](https://github.com/flaiker/prettier-printer)
It is however quite difficult, especially because of things like chained statements, comments inside of statements between tokens, pragmas, statements spanning across multiple lines etc...

I might get back to it in the future but currently it is on hold.

**Comment by larshp** [comment]
Shift + F1 upper casing keywords implemented in https://marketplace.visualstudio.com/items?itemName=larshp.vscode-abaplint

**Comment by andau** [comment]
No I am not aware of such a tool, but I will let the issue open, maybe there are some further projects mentioned beside the two above.

**Comment by larshp** [comment]
code inspector check for pretty printer use, https://docs.abapopenchecks.org/checks/06/
